const languages = {
  am: { description: "Amharic" },
  ar: { description: "Arabic" },
  bg: { description: "Bulgarian" },
  bn: { description: "Bengali" },
  ca: { description: "Catalan" },
  cs: { description: "Czech" },
  da: { description: "Danish" },
  de: { description: "German" },
  el: { description: "Greek" },
  en_GB: { description: "English (Great Britain)" },
  en_US: { description: "English (USA)" },
  en: { description: "English" },
  es_419: { description: "Spanish (Latin America and Caribbean)" },
  es: { description: "Spanish" },
  et: { description: "Estonian" },
  fa: { description: "Persian" },
  fi: { description: "Finnish" },
  fil: { description: "Filipino" },
  fr: { description: "French" },
  gu: { description: "Gujarati" },
  he: { description: "Hebrew" },
  hi: { description: "Hindi" },
  hr: { description: "Croatian" },
  hu: { description: "Hungarian" },
  id: { description: "Indonesian" },
  it: { description: "Italian" },
  ja: { description: "Japanese" },
  kn: { description: "Kannada" },
  ko: { description: "Korean" },
  lt: { description: "Lithuanian" },
  lv: { description: "Latvian" },
  ml: { description: "Malayalam" },
  mr: { description: "Marathi" },
  ms: { description: "Malay" },
  nl: { description: "Dutch" },
  no: { description: "Norwegian" },
  pl: { description: "Polish" },
  pt_BR: { description: "Portuguese (Brazil)" },
  pt_PT: { description: "Portuguese (Portugal)" },
  ro: { description: "Romanian" },
  ru: { description: "Russian" },
  sk: { description: "Slovak" },
  sl: { description: "Slovenian" },
  sr: { description: "Serbian" },
  sv: { description: "Swedish" },
  sw: { description: "Swahili" },
  ta: { description: "Tamil" },
  te: { description: "Telugu" },
  th: { description: "Thai" },
  tr: { description: "Turkish" },
  uk: { description: "Ukrainian" },
  vi: { description: "Vietnamese" },
  zh_CN: { description: "Chinese (China)" },
  zh_TW: { description: "Chinese (Taiwan)" },
};

const forEachLanguage = (fn) => Object.entries(languages).forEach(fn);

const getLanguagePart = ({ language }) => {
  const [firstPart] = language.split("_");
  return firstPart;
};

export { forEachLanguage, getLanguagePart };
